on:
  push:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkoutv2
      - name: Install Crystal
        uses: oprypin/install-crystalv1
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec
      - name: Build
        run: shards build
      - name: Check formatting
        run: crystal tool format; git diff --exit-code
